fixed issue where dump options failed if tmux session already existed

diff --git a/tmc b/tmc
--- a/tmc
+++ b/tmc
@@ -163,10 +163,11 @@ if [ -z "$CLUSTER_LINE" ]; then
 fi
 
 # check for existing tmux session of the specified cluster
-# FIXME: this should not error out if we're using one of the dump flags
-if [ -n "$(tmux ls 2>/dev/null | grep "cluster-$CLUSTER:")" ]; then
-	echo "error: tmux session cluster-$CLUSTER already exists" 1>&2
-	exit 3
+if [ -z "$DUMP_HOSTS" -a -z "$DUMP_TMUX_CMDS" ]; then
+	if [ -n "$(tmux ls 2>/dev/null | grep "cluster-$CLUSTER:")" ]; then
+		echo "error: tmux session cluster-$CLUSTER already exists" 1>&2
+		exit 3
+	fi
 fi
 
 # get hosts from cluster line
